### ISSUE TITLE
not deleting

### ISSUE THREAD

**Issue by anon97945** [Qwerty-Space/AntiDeletedAccountsBot#2]
hello, I'm using Rose as a groupmanager and she mutes new users, some of them were spam bots and never verified themselves so they stay with none permissions..now some of them got there account deleted but your not not deleting them. i think because they have non standard permissions? can you look into this?

**Comment by Qwerty-Space** [comment]
They will be kicked within the next hour.

The bot limits how often it checks groups for deleted accounts ONCE per hour, and only when a user sends a message, to filter out inactive groups.

**Comment by anon97945** [comment]
can i write u on pm?

**Comment by Qwerty-Space** [comment]
Upon further discussion with @anon97945, the bot is working as intended.  It removed the deleted account from the group, but does not remove the user's restrictions.
