### ISSUE TITLE
hello Team - the bot try kicked everytime old deleted admin or owner accounts... pls stop the try

### ISSUE THREAD

**Issue by FrankderReisende** [Qwerty-Space/AntiDeletedAccountsBot#3]
we have see, youre bot try to kick also deletet Admins or Owner Accounts...

when he cant kick, he try every 10 Minutes... we cant deletet in any groups there try to do it...

i think its, it possible stop try to kicks by old Deleted Account he cant dont kick because there admin or owner?

thank you

Telegram:

@Frank_Thureringen_36_Admin

**Comment by Qwerty-Space** [comment]
As I understand it, it's trying to kick the owner, who has deleted his account?

I will fix this soon.  Also, it should try every hour, not every 10 minutes

**Comment by FrankderReisende** [comment]
yes you have correct understand, and also a admin there promote by deleted owner account... there also have a deleted account ^^

**Comment by Qwerty-Space** [comment]
Should be fixed now.  Please let me know, so that I can close the issue

**Comment by FrankderReisende** [comment]
thank you verry mutch, its work :) you can close.

**Comment by Qwerty-Space** [comment]
Unfortunately this is an in-memory solution, so it will still give you the error occasionally.  I will make it delete the error automatically, however I recommend just moving to a new group
