### ISSUE TITLE
The bot does not delete deleted account

### ISSUE THREAD

**Issue by fiona102** [Qwerty-Space/AntiDeletedAccountsBot#6]
![Screenshot_2021-07-01-21-17-35-25](https://user-images.githubusercontent.com/86788806/124139448-d145a100-dab1-11eb-862a-8ce35db31a25.jpg)
Please fjx

**Comment by Qwerty-Space** [comment]
Unfortunately the bot is under a HUGE load, it got bigger than I ever thought it would.  So, I'm going to have to find the time to make it work better under load.  

Until now, it might be quite slow.

**Comment by Qwerty-Space** [comment]
Should be fixed in the latest update.
